version: '3.8'

services:
  socketio-server:
    build:
      context: ./socketio-server
    ports:
      - "8080:8080"
    # networks:
    #   - app-network

  next-app:
    build:
      context: ./next-app
    ports:
      - "80:80"
    # networks:
    #   - app-network


# networks:
#   app-network:
#     driver: bridge
